### PR TITLE
pulling highlight Json in views.py

### PR DESCRIPTION
**Pull request by Ramin-Farhadi**
We are pulling the JSON highlights in a hidden field by views.py

### CODE REVIEW

**Comment by jmbarne3** [comment]
Does it matter what order the highlights appear in? If so, how are we keeping track of the order?

**Comment by Ramin-Farhadi** [comment]
> Does it matter what order the highlights appear in? If so, how are we keeping track of the order?

I don't think order is important but It's an array of objects, so each object has own index.

**Comment by jmbarne3** [comment]
I can guarantee you the people using the tool are going to care what order the highlights appear in. They're going to want them to appear in the same order on the page as they appear in our tool. We can either embed the index in the ID, i.e. `id-highlight-{index}` or we can put the information elsewhere, like a data attribute, i.e. `data-order={index}`. Either way will work fine.

**Comment by Ramin-Farhadi** [comment]
> I can guarantee you the people using the tool are going to care what order the highlights appear in. They're going to want them to appear in the same order on the page as they appear in our tool. We can either embed the index in the ID, i.e. `id-highlight-{index}` or we can put the information elsewhere, like a data attribute, i.e. `data-order={index}`. Either way will work fine.

Ok I will work on that.

**Comment by jmbarne3** [comment]
I get the following output:

```[{"id":"id-1720800644207","data_order":2,"iconClass":"fa-face-smile fa m-2","description":"This is a smiley face."},{"id":"id-1720800655327","data_order":2,"iconClass":"fa-arrow-up fa m-2","description":"This is an up arrow."}]```

When I take the following steps:

1. Add an icon and description.
2. Add another icon and description.
3. Add a third icon and description.
4. Delete the first icon and description.
5. Save.

**Comment by Ramin-Farhadi** [comment]
> I get the following output:
> 
> `[{"id":"id-1720800644207","data_order":2,"iconClass":"fa-face-smile fa m-2","description":"This is a smiley face."},{"id":"id-1720800655327","data_order":2,"iconClass":"fa-arrow-up fa m-2","description":"This is an up arrow."}]`
> 
> When I take the following steps:
> 
> 1. Add an icon and description.
> 2. Add another icon and description.
> 3. Add a third icon and description.
> 4. Delete the first icon and description.
> 5. Save.

Logic added, I will be updated when we remove a story.

**Review by jmbarne3 — APPROVED** [review]
I'm going to approve this for now in the interest of moving things forward. However, I think we're going to take a look at this next week and see if there is an alternative to the way we handle the updating/saving of the values.

**Pull request merged**
